name: My-GithubActions-Bacics

on:
  push:
    branches: 
      - main
      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "hello world"
    - name: Print Hello Message 2nd step
      run: echo "hello from 2nd step"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: Print another Message
      run: echo "hello world another message"
