name: CI-CD-pipeline-to-AWS-Elastic-Bean-Stock 
env:
  EB_PACKAGE_S3_BUCKET_NAME: "vijolite-for-github"
  EB_APPLICATION_NAME: "hello_flask"
  EB_ENVIRONMENT_NAME: "My-Flask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{github.sha}}.zip"
  AWS_REGION_NAME: "us-east-1"
  

on:
  push:
    branches: 
      - main
      
jobs:
  my-ci-part:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
    - name: Create Zip deployment package
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
    

      
